import { useEffect, useState } from 'react';
import { ShieldCheck, Check, X } from 'lucide-react';
import { PageHeader } from '../../components/ui/PageHeader';
import { Card } from '../../components/ui/Card';
import { Badge } from '../../components/ui/Badge';
import { Button } from '../../components/ui/Button';
import { LoadingSkeleton } from '../../components/ui/LoadingSkeleton';
import { EmptyState } from '../../components/ui/EmptyState';
import { Alert } from '../../components/ui/Alert';
import { alerts } from '../../data/alerts';

export default function AIReviewPage() {
  const [isLoading, setIsLoading] = useState(true);
  const reviewQueue = alerts.filter((a) => a.severity !== 'info');

  useEffect(() => {
    const t = setTimeout(() => setIsLoading(false), 700);
    return () => clearTimeout(t);
  }, []);

  return (
    <div>
      <PageHeader
        title="AI Review"
        description="Recommendations generated by the predictive model, pending human approval."
      />

      <Alert variant="info" title="Human-in-the-loop by design" className="mb-5">
        Every AI-generated recommendation routes here before it can trigger a staffing or scheduling change.
        Nothing is auto-applied.
      </Alert>

      {isLoading ? (
        <LoadingSkeleton variant="list" rows={3} />
      ) : reviewQueue.length === 0 ? (
        <EmptyState
          icon={ShieldCheck}
          title="Review queue is clear"
          description="No AI recommendations are currently awaiting approval."
        />
      ) : (
        <div className="flex flex-col gap-3">
          {reviewQueue.map((item) => (
            <Card key={item.id} className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
              <div className="flex items-start gap-3">
                <span className="mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-brand-50 text-brand-600 dark:bg-brand-900/40 dark:text-brand-300">
                  <ShieldCheck className="h-4 w-4" />
                </span>
                <div>
                  <p className="text-sm font-medium text-ink">{item.title}</p>
                  <p className="mt-1 text-sm text-ink-muted">{item.detail}</p>
                  <Badge variant="neutral" className="mt-2">
                    {item.confidence}% confidence
                  </Badge>
                </div>
              </div>
              <div className="flex shrink-0 gap-2">
                <Button variant="secondary" size="sm" icon={X}>
                  Dismiss
                </Button>
                <Button size="sm" icon={Check}>
                  Approve
                </Button>
              </div>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
